# ===============================================
#          Immune cells
# ===============================================

[["Immune cells"]]
name = "Immune"
color = "#5353cc" # Blue-purple, parent color
markers = ["PTPRC"] # CD45, pan-immune
minor = [
    # --- Level 2: Lymphoid Lineage ---
    { name = "Lymphoid", color = "#1f77b4", markers = ["CD3D", "MS4A1", "NCAM1", "CD3E", "CD3G"], minor = [
        # Level 3: T cells
        { name = "T cells", color = "#1ba169", markers = ["CD3D", "CD3E", "CD3G", "TRAC", "CD8A"], minor = [
            # CD4+ T
            { name = "CD4+ T", color = "#2ca02c", markers = ["CD4", "CD40LG", "FOXP3", "IL7R", "CCR7"], minor = [
                { name = "CD4+ Tn",    color = "#11aa00", markers = ["TCF7", "SELL", "CCR7", "LEF1", "MAL"] },
                { name = "CD4+ Tm",    color = "#8cfd7e", markers = ["IL7R", "S100A4", "GZMK", "CCL4", "CAPG"] },
                { name = "CD4+ Tem",   color = "#55ff00", markers = ["GZMK", "KLRB1", "CCL5", "CXCR4"] },
                { name = "CD4+ Temra", color = "#00cc99", markers = ["CX3CR1", "FGFBP2", "GZMH", "TBX21"] },
                { name = "Treg",       color = "#3b845e", markers = ["FOXP3", "IL2RA", "CTLA4", "TNFRSF9", "RTKN2"] },
                { name = "Th17",       color = "#b0e313", markers = ["RORC", "IL17A", "IL17F", "CCR6", "STAT3", "TGFB1"] },
                { name = "Tfh",        color = "#10a674", markers = ["CXCR5", "BCL6", "IL21", "TOX", "TCF7"] }
            ]},
            # CD8+ T
            { name = "CD8+ T", color = "#ff7f0e", markers = ["CD8A", "CD8B", "GZMA", "GZMB"], minor = [
                { name = "CD8+ Tn",    color = "#ff9900", markers = ["TCF7", "SELL", "CCR7", "LEF1", "MAL"] },
                { name = "CD8+ Tm",    color = "#ffbb33", markers = ["IL7R", "EOMES", "GZMK", "CCL4", "CAPG"] },
                { name = "CD8+ Trm",   color = "#ffaa00", markers = ["ZNF683", "CD52", "HOPX", "S100A4"] },
                { name = "CD8+ Tem",   color = "#ff8800", markers = ["GZMK", "CCL3", "CXCR4", "KLRG1"] },
                { name = "CD8+ Temra", color = "#ff6600", markers = ["CX3CR1", "GZMH", "TBX21", "KLRD1"] },
                { name = "Tex",        color = "#cc5500", markers = ["PDCD1", "TOX", "LAG3", "HAVCR2", "CTLA4"] }
            ]},
            # NKT, MAIT
            { name = "NKT", color = "#04650d", markers = ["KLRD1", "NKG7", "TYROBP", "KIR3DL1", "CD160"] },
            { name = "MAIT", color = "#9467bd", markers = ["SLC4A10", "KLRB1", "ZBTB16"] }
        ]},
        # Level 3: B cells
        { name = "B cells", color = "#7ccbc5", markers = ["MS4A1", "CD19", "CD79A", "CD79B", "IGHM"], minor = [
            { name = "Naive B",     color = "#00e8d8", markers = ["TCL1A", "FCER2", "IGHD", "YBX3"] },
            { name = "Memory B",    color = "#00b3aa", markers = ["CD27", "IGHG1", "AIM2", "ITGB1"] },
            { name = "GC B",        color = "#005160", markers = ["LMO2", "CXCR4", "MKI67", "MEF2B"] },
            { name = "Plasmablast", color = "#629b92", markers = ["TXNDC5", "MYDGF"] },
            { name = "Plasma",      color = "#27a0a8", markers = ["JCHAIN", "XBP1", "SDC1", "MZB1"] }
        ]},
        # Level 3: NK cells
        { name = "NK cells", color = "#014431", markers = ["NCAM1", "NKG7", "KLRF1", "KLRD1"], minor = [
            { name = "CD56+CD16- NK", color = "#0c5d3d", markers = ["NCAM1", "KLRK1", "KIT", "GZMK"] },
            { name = "CD56-CD16+ NK", color = "#093d29", markers = ["FCGR3A", "NCR3", "GZMB", "PRF1"] }
        ]},
        # Level 3: ILC
        { name = "ILC", color = "#c5b0d5", markers = ["ID2", "IL7R", "RORC", "GATA3"] }
    ]},

    # --- Level 2: Myeloid Lineage ---
    { name = "Myeloid", color = "#d62728", markers = ["LYZ", "CD68", "ITGAM", "VCAN"], minor = [
        # Level 3: Monocytes
        { name = "Monocytes", color = "#1151b4", markers = ["FCN1", "S100A8", "S100A9", "CD14"], minor = [
            { name = "CD14+ Mono", color = "#1560bd", markers = ["FCN1", "HLA-DQB1", "S100A9", "CSF3R", "S100A8"] },
            { name = "CD16+ Mono", color = "#66ddff", markers = ["FCGR3A", "LST1", "LILRB2", "HK3"] },
            { name = "CD14+CD16+ Mono", color = "#003a6c", markers = ["NFKBIA", "NFKB1", "NLRP3", "HLA-DQA1"] }
        ]},
        # Level 3: Macrophages
        { name = "Macrophages", color = "#e377c2", markers = ["CD68", "CD163", "APOE", "C1QA", "MSR1"], minor = [
            { name = "Reg TAM",    color = "#6a5bb1", markers = ["ARG1", "MRC1", "CD274", "CX3CR1"] },
            { name = "Inflam TAM", color = "#333399", markers = ["IL1B", "CCL3", "CXCL1", "CXCL2"] },
            { name = "IFN TAM",    color = "#5729ce", markers = ["IDO1", "ISG15", "CXCL10", "STAT1"] },
            { name = "Angio TAM",  color = "#9966cc", markers = ["VEGFA", "SPP1", "FGF2", "MMP9"] },
            { name = "Prolif TAM", color = "#cc99ff", markers = ["MKI67", "CDK1", "PCNA"] },
            { name = "LA TAM",     color = "#9bacd8", markers = ["APOC1", "APOE", "FABP5"] },
            { name = "TRM TAM",    color = "#0000aa", markers = ["LYVE1", "FOLR2", "CX3CR1", "MERTK"] }
        ]},
        # Level3： Dendritic cells
        { name = "Dendritic cells", color = "#8c564b", markers = ["CD74", "FLT3", "ITGAX", "CD1C"], minor = [
            { name = "pDC",  color = "#50a7d9", markers = ["LILRA4", "GZMB", "IL3RA", "TCF4"] },
            { name = "cDC1", color = "#a1caf1", markers = ["CLEC9A", "XCR1", "CADM1"] },
            { name = "cDC2", color = "#5a79ba", markers = ["CD1C", "FCER1A", "CLEC10A"] },
            { name = "cDC3", color = "#4c69a7", markers = ["LAMP3", "CCR7", "FSCN1", "CST7"] }
        ]},
        # --- Other Granulocytes ---
        { name = "Mast cells",  color = "#1E90FF", markers = ["TPSAB1", "KIT", "CPA3", "TPSB2", "FCER1A"] },
        { name = "Neutrophils", color = "#a3e3ed", markers = ["FCGR3B", "CXCR2", "CSF3R"] },
        { name = "Eosinophils", color = "#ff99cc", markers = ["CCR3", "FUT4"] },
        { name = "Basophils",   color = "#cc99ff", markers = ["CD63", "ENPP3"] }
    ]}
]

# ===============================================
#          Stromal Cells
# ===============================================

[["Stromal cells"]]
name = "Stromal"
color = "#ffbb78"
markers = ["COL1A1", "PECAM1", "PDGFRA", "PDGFRB", "ACTA2"]
minor = [
    { name = "Endothelial cells", color = "#fecb51", markers = ["PECAM1", "VWF", "CDH5", "RAMP2", "ENG"], minor = [
        { name = "Arterial EC",   color = "#ffae42", markers = ["SEMA3G", "GJA5", "BMX"] },
        { name = "Venous EC",     color = "#ff9e2c", markers = ["ACKR1", "SELP", "NRG1"] },
        { name = "Capillary EC",  color = "#ffb347", markers = ["RGCC", "CA4", "CD36"] },
        { name = "Lymphatic EC",  color = "#e7e04e", markers = ["PROX1", "LYVE1", "CCL21"] },
        { name = "TipEC",         color = "#ffcc66", markers = ["COL4A1","KDR","ESM1"] },
        { name = "EndoMT",        color = "#ffa700", markers = ["PDGFRB"] }
    ]},
    { name = "Fibroblasts", color = "#FF8C00", markers = ["ACTA2", "COL1A1", "COL3A1", "COL1A2", "DCN"], minor = [
        { name = "iCAF",    color = "#ee6600", markers = ["CFD", "APOD", "IGF1", "CXCL12", "MGP", "FAP"] },
        { name = "mCAF",    color = "#e68750", markers = ["POSTN", "FN1", "VCAN", "CTHRC1", "COL1A2"] },
        { name = "pCAF",    color = "#f08f00", markers = ["SCG2", "IGFBP2", "HIST1H4C", "PLAU"] },
        { name = "meCAF",   color = "#ffaa66", markers = ["NDRG1", "BNIP3", "TMEM158", "ADM"] },
        { name = "EndMTCAF",color = "#c56543", markers = ["PLVAP", "RAMP2", "RGCC"] },
        { name = "pnCAF",   color = "#e1583f", markers = ["S100B", "GPM6B", "PLP1"] },
        { name = "apCAF",   color = "#fcb001", markers = ["HLA-DRA", "LYZ", "TYROBP"] }
    ]},
    { name = "Pericytes", color = "#b86d29", markers = ["RGS5", "MYH11", "PDGFRB", "MCAM"] },
    { name = "Smooth muscle cells", color = "#FFA07A", markers = ["TAGLN", "MYH11", "DES", "CNN1", "ACTA2"] }
]

# ===============================================
#          Epithelial & other Cells
# ===============================================

[["Epithelial cells"]]
name = "Epithelial"
color = "#f19cbb"
markers = ["EPCAM", "KRT19", "KRT18", "KRT8", "CDH1"]

[["Melanocytes"]]
name = "Melanocyte"
color = "#36454F"
markers = ["MLANA", "TYRP1", "TYR", "MITF"]

[["Schwann cells"]]
name = "Schwann"
color = "#304655"
markers = ["S100B", "CRYAB", "CDH19", "SOX10", "PLP1"]

[["Adipocytes"]]
name = "Adipocyte"
color = "#DAA520"
markers = ["ADIPOQ", "LEP", "FABP4", "PPARG", "PLIN1"]

[["RBC"]]
name = "RBC"
color = "#990000"
markers = ["HBB", "HBA1", "HBA2"]